ubccr/hpc-toolset-tutorial

- docker-compose.yml
ref: https://docs.docker.com/compose/compose-file/#init
ran 14 jobs
before:
```
[hpcadmin@frontend ~]$ ssh cpn02 'ps aux --forest' ; ssh cpn01 'ps aux --forest'
Warning: Permanently added 'cpn02,172.27.0.8' (ECDSA) to the list of known hosts.
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.2 146476  6000 ?        Ss   20:25   0:01 /usr/sbin/slurmd -Dvvv
munge       13  0.0  0.1 221676  2560 ?        Sl   20:25   0:00 /usr/sbin/munged
root        20  0.0  0.1 112936  2920 ?        Ss   20:25   0:00 /usr/sbin/sshd
root       174  0.0  0.4 150620  8884 ?        Ss   21:55   0:00  \_ sshd: hpcadmin [priv]
hpcadmin   176  0.0  0.2 150620  4220 ?        S    21:55   0:00      \_ sshd: hpcadmin@notty
hpcadmin   177  0.0  0.1  55200  3980 ? …
```
> Allow Compute Nodes to reap processes

- base/install.sh
- coldfront/entrypoint.sh
- docker-compose.yml
- ldap/Dockerfile
- ldap/base.config
- ldap/install.sh
- ondemand/entrypoint.sh
- slurm/entrypoint.sh
- slurm/install.sh
- xdmod/entrypoint.sh
This adds LDAP container that all other containers except MySQL will depend on.
The LDAP data is populated from previous data used to populate local passwd database.  Because Docker can't build files from symlinks, I had to make a copy of `base.config` that is shared between `base` and `ldap` containers.
I integrated LDAP using SSSD on all containers, this is not yet tested fully. I only tested with interactive builds of the base container.  Once OnDemand 1.8 gets its first tag we can update OnDemand to that version for LDAP integration using Dex.
Still need XDMOD and coldfront integration to the LDAP container
> Use LDAP for users

- base/install.sh
Seems LDAP container and LDAP service take a little bit of time to become ready and this was causing SSSD to go offline for default of 60 seconds. So a container would start but it would be another 60 seconds before ID mapping would work.
I added a LDAP wait function to all entrypoints using LDAP. Also reduced offline times for SSSD to that if SSSD is started with LDAP not ready, it will retry faster.
Below is logs from before I added LDAP wait.  It's not every time that LDAP has to wait, but this should reduce factors that could make containers not respond well to things talking to LDAP.
```
frontend     | (Tue Jul  7 13:34:38 2020) [sssd[be[default]]] [sdap_id_op_connect_done] (0x0020): Failed to connect, going offline (5 [Input/output error])
```
Then
```
frontend     | (Tue Jul  7 …
```
> Ensure SSSD handles LDAP service not being ready

- ondemand/Dockerfile
- ondemand/bc_desktop.yml
- ondemand/cluster-config.yml
- ondemand/install.sh
- slurm/install.sh
This does not yet work 100%.  Right now the desktop app launches successfully but I'm unable to connect to the noVNC session.
> Add support for OnDemand bc_desktop app

- base/install.sh
- coldfront/coldfront-nginx.conf
- coldfront/install.sh
- ondemand/install.sh
- xdmod/conf/httpd.conf
- xdmod/conf/simplesamlphp/metadata/saml20-idp-hosted.php
- xdmod/install.sh
- xdmod/scripts/xdmod-setup-sso.sh
We have a student worker who was having certificate issues on Ubuntu and said changing the CN to `localhost` solved their issue. Without this change they were never able to even bypass the self signed cert warnings.
FWIW He also verified that exporting the container CA to Firefox got rid of all cert warnings, but not necessary to do that. This was command I had them use:
```
docker cp ondemand:/etc/pki/tls/ca.crt ./ca.crt
```
> Use single certificate and CA for all containers

- base/install.sh
Makes life easier when running jobs from the command line, no more:
```
[hpcadmin@frontend ~]$ sbatch ba-bash: _get_comp_words_by_ref: command not found
-bash: _filedir: command not found
d-bash: _get_comp_words_by_ref: command not found
-bash: _filedir: command not found
```
> add bash completion

- coldfront/install.sh
- coldfront/local_settings.py
Do not merge yet. This commit configures Coldfront for authenticating against Dex via OAuth2/OpenID. Requires OSC/ondemand#589 that will be included in OOD v1.8.3. Also requires updating `ood_portal.yml` with the correct static_clients and secrets.
> Add support for OAuth2/OpenID authentication in Coldfront.

- ondemand/install.sh
- add ondemand as a host that can be accessed from the shell app
- specify ondemand as the default dev host
- setup hpcadmin's bash_profile to load the ondemand scl for development
> Enable ssh to ondemand for app dev

- coldfront/install.sh
- coldfront/local_settings.py
Currently, OAuth2/OpenID authentication using Dex IdP does not support logging out. A large part of the Coldfront tutorial is showing how the various user account roles (Admin, PI, user, etc.) interact with the application. This requires easily logging in/out as different accounts. To support this we're adding back in LDAP authentication. Coldfront is now configured to support 3 backend authentication mechanisms (local login, LDAP login, and OAuth2/OpenID via Dex). This allows us to demo different user accounts while still showing how SSO integration works.
> Add back LDAP authentication to Coldfront.

- hpcts
To make things easier for tutorial participants, we'll recommend using
this `hpcts` helper script. There's 3 verbs start, stop, cleanup.
- `start` will pull the latest container images from docker hub and
start all the container services.
- `stop` will stop and remove all containers and volumes
- `cleanup` will stop and REMOVE all images. Next time start is run they
will be re-fetched.
> Tidy up helper script to be more intuitive.

- coldfront/README.md
I suggest that (since this will be discussed in detail in the XDMoD section of the tutorial) it is not necessary to include the gory details inline. 
If we really want to include the script contents inline then they will need to be an exact copy of the actual script.
> Remove the incorrect copy of the shred-ingest-aggregate-all from the markdown

- ondemand/cluster-config.yml
- ondemand/motd
- xdmod/install.sh
the trailing lines at the end of the motd is intentional, because it
appears whenever you login in via the shell to the ondemand host
This keeps manual step required to enable XDMoD integration in OnDemand, since there isn't value in participants executing shell commands do all the steps.
> Partly setup XDMoD/OOD integration at build time

- xdmod/entrypoint.sh
- xdmod/install.sh
The scripts are structured to split out different categories of setup. The
install script is split into two sections: install of packages and
dependencies and update of mandatory O/S configuration.
We don't want the install script to contain tutorial-specifc configuration since we
discuss this at a different point.
Instead the tutorial-specific configuration happens when we discuss the
entry_point script.
> Move the editing of the configuration files into the correct place.

- ondemand/initializers/dashboard.rb
I wasn't sure where to do this. If you have a suggestion let me know.
The block of code in this initializer executes every time the dashboard app of OnDemand starts up. It adds the block to the ~/.bash_profile if that file can be read and written to and doesn't already load scl when ssh-ing to the ondemand host.
> Enable scl for hpcadmin in bash_profile

- ondemand/README.md
As I was following this tutorial, I noticed that this link wasn't clickable like others of similar nature in the repo.
> Make link clickable

- ondemand/README.md
- `mkdir` can't create the `~/ondemand/dev` directory without the `-p` option
- The instructions were unclear about connecting to the `ondemand` host to run the rest of the setup commands.
> Fixes for OnDemand setup instructions

- docker-compose.yml
Fixes #119. After stopping/starting containers the `hpcadmin` user could no longer submit jobs without specifying a slurm account, even though the slurm association had a DefaultAccount set for that user. This appears to be due to the slurm state directories not persisting after a restart. This PR adds volumes for slurmd, slurmctld, and slurmdbd for the slurm state directory.
> Mount slurm state directories as volumes.

- xdmod/install.sh
- Updated the supremm rpm install to take into account which
architecture it's being built on and install the correct rpm.
Currently supported architectures are: x86_64, and aarch64 ( arm64 )
> Updating XDMoD's install script

- ondemand/entrypoint.sh
Fixes #134 by running `nginx_stage` to clean the PUNs that may be left over from the last startup.
> run nginx clean on start for safe restart

- docker-compose.yml
This fixes: https://github.com/ubccr/hpc-toolset-tutorial/issues/135 
When doing a `docker-compose down` XDMoD's etc directory would be reset to
container default, adding a new volume ensures that this persists between
docker-compose downs and ups.
> Adding a new volume for xdmods etc directory

- xdmod/setup.sh
Fixes permission issues due to the portal_settings.ini , ondemand.ini, and supremm.ini files having owner and group set to `root:apache` instead of `apache:xdmod` which is required to shred, ingest and aggregate data.
> Fix permissions for portal settings files

- ondemand/README.md
OOD needs to use `release_3.0` branch for the dashboard setup because 3.0 is what's installed in the container.
> OOD needs to use release_3.0 branch

- coldfront/install.sh
- ondemand/install-dex-arm64.sh
- slurm/install.sh
- xdmod/install.sh
'docker-compose' commands can be used to rebuild and run containers
> updates from Gateways24

- ondemand/Dockerfile
install rdoc 6.3.3 for job composer, fixing an issue with the Job Composer in these containers.
> install rdoc 6.3.3 for job composer

- ondemand/README.md
- ondemand/jupyter/template/script.sh.erb
- slurm/install.sh
> update jupyter in the OOD demo

- database/skip-name-resolve.cnf
The changes in this PR arose from a desire to be able to choose between having a fully configured & populated XDMoD database & a fully configured but _**empty**_ XDMoD database. The method of having a fully configured by empty database, from investigation, seemed to be: remove / rename the `database/xdmod.dump` file and the included bash scripts would take care of the rest. Upon testing it was found that the scripts that handle the setup of users and databases for XDMoD, when the dump is not present, were relying on MariaDB allowing / using hostname's for database users. This conflicted with a new(-ish) MariaDB configuration `skip-name-resolve` being enabled, which means that all database user `hosts` would need to be IP Addresses not hostnames, this was causing said scripts to error out …
> Adding disable-skip-name-resolve to mysql
