ubccr/hpc-toolset-tutorial

slurm/slurm.conf

allow to have multiple node jobs.

Allow for 2 nodes jobs

---

docs/applications.md

I think this makes the usernames and passwords stand out a bit more.

Make usernames and passwords more noticeable

---

xdmod/Dockerfile
xdmod/conf/httpd.conf
xdmod/conf/simplesamlphp/config/authsources.php
xdmod/conf/simplesamlphp/config/config.php
xdmod/conf/simplesamlphp/metadata/saml20-idp-hosted.php
xdmod/conf/simplesamlphp/metadata/saml20-idp-remote.php
xdmod/conf/simplesamlphp/metadata/saml20-sp-remote.php
xdmod/entrypoint.sh
xdmod/install.sh
xdmod/scripts/xdmod-setup-sso.sh

This "works" but has an unrelated issue: 'Could not execute: /usr/sbin/sendmail -t -i' that will be resolved with getting sendmail to "work" with xdmod.  However I think since it is not related to SSO it does not belong in this PR

Enable SSO for XDMoD Docker

---

xdmod/Dockerfile
xdmod/bin/sendmail

XDMoD needs to send email, if it doesnt things will error.
This will output all email that XDMoD would send to /tmp/mailoutput.txt for viewing if wanted.

fake sendmail for xdmod

---

docs/applications.md

XDMoD SSO Documentation updates.

Add documentation for XDMoD SSO

---

coldfront/entrypoint.sh
ondemand/entrypoint.sh
slurm/entrypoint.sh
xdmod/entrypoint.sh

Move sshd higher in the chain to be able to help in debugging.
Make sure sssd starts by making sure the pid has been removed
Make sure xdmod starts by making sure httpd pid has been removed.

make sure sssd starts;move sshd start up

---

xdmod/install.sh

update to xdmod9.0 (rc1) so the url is temporary but will allow full integration.

update to xdmod9.0

---

README.md
coldfront/README.md
database/create-xdmod-db.sh
docker-compose.yml
docs/applications.md
mongodb/setup.sh
ondemand/README.md
slurm/Dockerfile
slurm/entrypoint.sh
slurm/install.sh
slurm/pmlogger-supremm.config
slurm/slurm-epilog.sh
slurm/slurm-prolog.sh
slurm/slurm.conf
xdmod/entrypoint.sh
xdmod/install.sh
xdmod/scripts/helper-functions.tcl
xdmod/scripts/shred-ingest-aggregate-all.sh
xdmod/scripts/supremm.py
xdmod/scripts/xdmod-setup-supremm.tcl

Updates Open XDMoD to have the Job Performance Module and SUPREMM; adds pvp to the slurm cluster for Job Performance Metrics.
This is needed for better demonstration of Open XDMoD full integration with OnDemand.
Also "rebrands" XDMoD -> Open XDMoD to be differentiate between the XSEDE version and the community version

Update Open XDMoD and SLURM for Job Perf and SUPREMM

---

ondemand/install.sh
slurm/install.sh
slurm/slurm.conf

- add jupyter to compute node including required libs for example batch job
- add debug partition for demonstrating enabling specifying the partition in an app
- make hpcadmin an OnDemand app developer

Modifications to support OnDemand app development tutorial with Jupyter 

---

coldfront/README.md
docs/docker_tips.md
docs/getting_started.md
docs/requirements.md

Updates to getting started, requirements, and docker tips instructions

Updated instructions

---

slurm/install.sh

We want all the negative and positive benefits of stress...
We really just want to have graphs that are more than just 0 cpu usage
https://linux.die.net/man/1/stress

Add stress package for job performance measures

---

ondemand/install.sh

1. Fix Shell app access to compute nodes 
2. Add starting app for Passenger tutorial

OnDemand shell and passenger fix

---

ondemand/install.sh
xdmod/conf/simplesamlphp/config/authsources.php
xdmod/conf/simplesamlphp/metadata/saml20-idp-hosted.php
xdmod/conf/simplesamlphp/metadata/saml20-idp-remote.php
xdmod/install.sh
xdmod/scripts/xdmod-setup-sso.sh

This will allow Open XDMoD to use DEX once a new release is build after https://github.com/ubccr/xdmod/pull/1378 is merged

Configures Open XDMoD to use DEX

---

ldap/install.sh
xdmod/conf/simplesamlphp/config/authsources.php

gives ldap users real names, and has xdmod use them as part of login

Give Users Real Names

---

base/install.sh

Fixes #47 but this needs to be tested by whoever was having the issue that we created #20 for to make sure that still works

Update crt to work on macos Catalina and chrome

---

ondemand/Dockerfile
ondemand/install.sh
ondemand/motd

the motd adds relevant tutorial links to OnDemand
it also postpones fixing a cosmetic bug where
with no MOTD the widgets hug the right of the screen

add motd to OnDemand

---

docs/getting_started.md
docs/requirements.md

updated instructions for starting up containers and add url for docker

updated startup instructions

---

coldfront/README.md
docs/applications.md
docs/docker_tips.md
docs/getting_started.md
docs/requirements.md

updated navigation, clarified some instructions, and made the applications page more uniform between the different container sections

reworked navigation

---

ondemand/README.md
ondemand/motd

Add a notes section to the MOTD in the OnDemand dashboard with some useful text for copying/pasting including the directions for enabling XDMoD integration.

OnDemand motd and readme updates

---

xdmod/conf/simplesamlphp/config/authsources.php
xdmod/install.sh

xdmod9.0-rc3

---

ondemand/README.md

500 doesn't actually work because of the 200 steps.

change default memory in ood tutorial

---

coldfront/README.md

Removed large video files from repo (sorry!) and updated with links to google drive

Video updates

---

docs/requirements.md

since we had one user notice that they had something running on the machine.

Note about ports not available

---

xdmod/README.md

Removes inaccurate statements regarding creation of databases.
@plessbd was concerned about the Open XDMoD database documentation:
https://github.com/ubccr/xdmod/pull/1410#issuecomment-670162899

Update asciinema recordings

---

xdmod/install.sh

update to the final versions vs the RC ones.
Should go against a different branch / tag than the PEARC tutorial if we want to maintain "exactness"

Update to final 9.0 XDMoD and related Releases

---

database/create-xdmod-db.sh
xdmod/Dockerfile
xdmod/historical/add-historical.sh
xdmod/historical/names.slurm.csv
xdmod/historical/resource_specs.json
xdmod/historical/resources.json

Since we dont have as much time in the Gateways 2020 tutorial/demo adding historical data to show off what we would usually have happen while doing the tutorial

Add historical data for gateways2020

---

database/group_concat.cnf
docker-compose.yml

XDMOD needs to have a bigger group_concat length.

Add group_concat setting to mysql for xdmod

---

ondemand/README.md

Minor tweaks for the OnDemand tutorial.

Some link and filename fixes.

---

ondemand/README.md

use the right .env.local file as was pointed out during the tutorial.

use the right .env.local file

---

ondemand/README.md

This is just more README updates for the OOD tutorial.
Barring anything unforeseen, I believe this is the last OOD update we'll need to make.

finish out ood tutorial

---

xdmod/install.sh
xdmod/scripts/supremm.py

No need to install python2 now that we are on Rocky 8.

Remove unneeded python2 dependencies.

---

xdmod/install.sh

Updating the version of XDMoD to the latest available ( 10.0.2-2 at the time of this PR )

Updating xdmod to 10.0.2-2

---

ondemand/initializers/dashboard.rb

This fixes #166. @johrstrom Can you review quick just to double just this isn't needed any more?

Remove scl_source

---

ondemand/README.md

don't use release_2.0 in ood

---

ondemand/Dockerfile

add libyaml-devel to ood container

---

ondemand/README.md

Typo in README.md

---

slurm/install.sh
xdmod/install.sh

correct turbovnc link because it's changed at some point.

minor corrections over time

---

coldfront/README.md
xdmod/README.md

to present at the Global OnDemand conference.  Also revised some of the original tutorial for formatting reasons and minor fixes.

Added docs for xdmod-ood integration tutorial
